Repository nuxt/fonts, pull requests merged in 2024-08, with the labels that each got.

#205 chore: switch to tinyglobby to drop 21 dependencies
  package.json
  pnpm-lock.yaml
  src/providers/local.ts
Labels: size:XS, lgtm

#228 refactor(devtools): enhance UI with improvments
  client/app.vue
Labels: enhancement, size:L, lgtm

#233 docs(usage): add callout to escape invalid characters in Tailwind config
  docs/content/1.get-started/3.usage.md
Labels: documentation, size:XS, lgtm
