Repository nuxt/fonts, pull requests merged in 2024-07, with the labels that each got.

#192 fix(adobe): use provided `css_names` from API
  src/providers/adobe.ts
Labels: bug, size:XS, lgtm

#196 fix(fontsource): use `/variable` endpoint for retrieving variable axes
  playground/nuxt.config.ts
  playground/pages/providers/fontsource.vue
  src/providers/fontsource.ts
  test/basic.test.ts
Labels: bug, size:M, lgtm

#206 docs: fix open an issue link on installation page
  docs/content/1.get-started/1.installation.md
Labels: documentation, size:XS, lgtm
