Repository nuxt/fonts, pull requests merged in 2024-09, with the labels that each got.

#133 feat: googleicons provider
  docs/content/1.get-started/4.providers.md
  playground/pages/providers/googleicons.vue
  src/module.ts
  src/providers/googleicons.ts
Labels: size:L, lgtm

#225 feat: allow experimentally disabling local fallbacks
  docs/content/1.get-started/2.configuration.md
  src/module.ts
  src/providers/adobe.ts
  src/providers/bunny.ts
  src/providers/fontshare.ts
  src/providers/fontsource.ts
  src/providers/google.ts
  src/providers/googleicons.ts
  src/types.ts
  test/basic.test.ts
Labels: enhancement, size:M, lgtm

#251 docs: update installation
  docs/content/1.get-started/1.installation.md
Labels: documentation, size:S

#253 docs: various improvements ✨
  docs/app.config.ts
  docs/app.vue
  docs/components/AppFooter.vue
  docs/components/AppHeader.vue
  docs/components/AppLogo.vue
  docs/components/HeroBackground.vue
  docs/components/OgImage/OgImageDocs.vue
  docs/nuxt.config.ts
  docs/nuxt.schema.ts
  docs/pages/[...slug].vue
  docs/pages/index.vue
  docs/tailwind.config.ts
  pnpm-lock.yaml
Labels: documentation, size:XL
